Sivigik/urls.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, include, url
from django.contrib import admin

from Sivigik.settings import IS_MAINTENANCE

from sitemap import *

admin.autodiscover()
sitemaps = {
    'main': BaseSitemap,
    'articles':ArticleSitemap,
    'category':CategorySitemap,
}

if IS_MAINTENANCE:
    urlpatterns = patterns('',
        url(r'^admin/', include(admin.site.urls)),
        url(r'', include('maintenance.urls', namespace='maintenance')),
)
else: 
    urlpatterns = patterns('',
        # Examples:
        # url(r'^$', 'Sivigik.views.home', name='home'),
        # url(r'^blog/', include('blog.urls')),
	    url(r'^article/', include('article.urls', namespace="article")),
        url(r'^admin/', include(admin.site.urls)),
	    url(r'^$', include('home.urls', namespace="home")),
	    url(r'^category/', include('home.urls', namespace="home")),
        url(r'^author/', include('author.urls', namespace="author")),
        url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    )

home/urls.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
	url(r'^$', views.home, name='index'),
    url(r'^(?P<category_name>[A-Za-z]+)/$', views.category, name='category'),
)

article/models.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar. If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from home.models import Event
from author.models import Author

class Article(models.Model):
    event = models.ForeignKey(Event)
    author = models.ForeignKey(Author)
    is_beta = models.BooleanField()
    modifiers = models.ManyToManyField(Author, related_name='modifiers+')

    def get_absolute_url(self):
        return '/article/' + str(self.id) + '/'

    def get_edit_url(self):
        return '/article/edit/' + str(self.id) + '/'
    def get_as_dict(self):
        returned = {}
        returned['event'] = self.event.id
        returned['author'] = self.author.id
        returned['is_beta'] = self.is_beta
        returned['modifiers'] = []
        for m in self.modifiers.all():
            returned['modifiers'].append(m.id)
        #returned['parts'] = []
        #for p in self.parts:
        #    returned['parts'].append(p.id)
        return returned


class Part(models.Model):
    text = models.TextField()
    title = models.CharField(max_length=200)
    article = models.ForeignKey(Article, related_name='parts')
    def get_as_dict(self):
        returned = {}
        returned['text'] = self.text
        returned['title'] = self.title
        returned['article'] = self.article.id
        return returned

home/models.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.db import models

import datetime
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=200)
    displayed_name = models.CharField(max_length=200)
    comment = models.TextField()
    def __unicode__(self):
        return self.name + " : " + self.comment
    def get_as_dict(self):
        returned = {}
        returned['name'] = self.name
        returned['displayed_name'] = self.displayed_name
        returned['comment'] = self.comment
        return returned

class Event(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date publication')
    category = models.ForeignKey(Category)
    image = models.ImageField(null=True, blank=True, upload_to="imgArticles/")
    is_pinned = models.BooleanField()
    def __unicode__(self):
        return self.name
    def get_as_dict(self):
        returned = {}
        returned['name'] = self.name
        returned['pub_date'] = {'year'       : self.pub_date.year,
                                'month'      : self.pub_date.month,
                                'day'        : self.pub_date.day,
                                'hour'       : self.pub_date.hour,
                                'minute'     : self.pub_date.minute,
                                'second'     : self.pub_date.second,
                                'microsecond': self.pub_date.microsecond,
                                }
        returned['category'] = self.category.id
        try:
            returned['image'] = self.image.file.name
        except ValueError:
            returned['image'] = ''
        returned['is_pinned'] = self.is_pinned
        return returned

class GoodSite(models.Model):
    name = models.CharField(max_length=200)
    comment = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    def __unicode__(self):
        return self.name + " : " + self.comment
    def get_as_dict(self):
        returned = {}
        returned['name'] = self.name
        returned['comment'] = self.comment
        returned['link'] = self.link
        return returned

def get_pinned_events():
    """Returns the pinneds events."""
    return Event.objects.filter(is_pinned=True)[:2]

def get_latest_events():
    """ Returns the last published events."""
    return Event.objects.filter(pub_date__lte=timezone.now()).filter(article__is_beta=False).filter(is_pinned=False).order_by('-pub_date')[:4]

def get_events_by_category(category):
    returned_events = []
    for e in Event.objects.all().order_by('-pub_date'):
        if e.category == category and e.pub_date < timezone.now():
            returned_events.append(e)
    return returned_events

def get_good_sites():
    """Returns the good sites list."""
    return GoodSite.objects.all()

def get_category_by_name(category_name):
    for c in Category.objects.all():
        if c.name == category_name:
            return c

def get_beta_events():
    return Event.objects.all().filter(article__is_beta=True)

home/views.py
#This file is part of Sivigik.
#
#Foobar is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Foobar is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
from django.shortcuts import render, get_object_or_404

from django.utils import timezone

from django.views import generic

from home.models import get_latest_events, get_good_sites, get_events_by_category, get_category_by_name, get_beta_events, Category, get_pinned_events

def home(request):
    """Displays the home page."""
    pinned = get_pinned_events()
    event_list = get_latest_events()
    good_sites_list = get_good_sites()

    return render(request, 'home/home_base.html', {'event_list'     :event_list,
                                                   'good_sites_list':good_sites_list,
                                                   'pinned':pinned})
def category(request, category_name):
    """Display the asked category"""
    if category_name == 'beta':
        event_list = get_beta_events()
        category = Category(name='B&ecirc;ta', displayed_name='B&ecirc;ta', comment='Articles en b&ecirc;ta')
    else:
        category = get_category_by_name(category_name)
        event_list = get_events_by_category(category)

    return render(request, 'home/home_base.html', {'event_list' :event_list,
                                                   'category':category})

home/templates/home/home_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load cache %}

{%block style %}<link rel="stylesheet" href="{% static 'home/style.css' %}" />{%endblock %}

{% block title %}
    {% if category %}
        {{category.name|safe}}
    {% else %}
        Accueil
    {% endif %}
{%endblock%}
{% block article_title %}
    {% if category %}
        {{category.displayed_name|safe}}
    {% else %}
        Accueil
    {% endif %}
{%endblock%}
{% block intro %}
{% if category %}
<p></p>
{%else%}
<p>Sivigik est un site de passionnés de <strong>bidouilles et bricolages</strong> en informatique, électronique ou encore en mécanique. Nous aurons à coeur de vous faire découvrir nos réalisations !</p>
{%endif %}
{% endblock %}
{% block bulle %}

{% if category.comment %}
    <div id="good_sites">
        {{ category.comment | safe }}
    </div>
{%endif%}
{% if good_sites_list %}
{% cache 21600 good_sites %}
    <div id="good_sites">
    <h3>Quelques sites à visiter :</h3>
    <ul>
    {% for site in good_sites_list %}
        <li><a href='http://{{site.link}}'>{{site.name}}</a><br/><div class="comment">{{site.comment}}</div></li>
    {% endfor %}
    </ul>
    </div>
{%endcache%}
{% endif %}
{% endblock %}
{% block content %}
    <div id='pinned'>
            <table>
        {%for event in pinned%}
            {%for article in event.article_set.all %}
            <tr>
                <td class="image"><a href="/article/{{article.pk }}">
                {% if event.image %}
                <img src="{{MEDIA_URL}}{{event.image}}" alt="Img"/>
                {% else %}
                <img src="/static/Svgk.png" alt="Img"/>
                {% endif %}
                </a>
                </td>
                <td><h3>{{event.name}}</h3></td>
                <td><em>par {{article.author.user.username}}</em></td>
            </tr>
            {%endfor%}
        {%endfor%}
            </table>
    </div>
    <div id='events'>
{% cache 10800 event_list event_list%}
{% if event_list %}
    <table>
    {% for event in event_list %}
    {% for article in event.article_set.all %}
        {% if category.comment%}
        {% if not article.is_beta or user.is_authenticated %}
    <tr>
        <td class="image"><a href="/article/{{article.pk }}">
        {% if event.image %}
        <img src="{{MEDIA_URL}}{{event.image}}" alt="Img"/>
        {% else %}
        <img src="/static/Svgk.png" alt="Img"/>
        {% endif %}
        </a>
        </td>
        <td><h3>{{event.name}}</h3></td>
        <td><em>par {{article.author.user.username}}</em></td>
    </tr>
        {%endif%}
        {%endif%}
        {%if good_sites_list%}
    <tr>
        <td class="image"><a href="/article/{{article.pk }}">        
        {% if event.image %}
        <img src="{{MEDIA_URL}}{{event.image}}" alt="Img"/>
        {% else %}
        <img src="/static/Svgk.png" alt="Img"/>
        {% endif %}
        </a></td>
        <td><h3>{{event.name}}</h3></td>
        <td><em>par {{article.author.user.username}}</em></td>
    </tr>
    
        {%endif%}
    {% endfor %}
    {% endfor %}
    </table>
{% else %}
    <table>
    <tr>
    <td>
    <h3>Pas (encore !) d'évènements disponibles.</h3>
    </td>
    </tr>
    </table>
{% endif %}
{% endcache %}
    </div>

{% endblock %}